import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}


// const handleFileChange = (e) => {
//   const etudiant = new Etudiant(
//     formData.name,
//     formData.filiereId,
//     formData.matricule,
//     formData.numero,
//     formData.email,
//     formData.niveau,
//     formData.password,
//     e.target.files[0]
//   );
//   dispatchEvent(createEtudiant(etudiant));
//   setFormData({ ...formData, photo: e.target.files[0] });
// };